version: "3.8"

services:
  client:
    build:
      context: ./tmdb-client
      dockerfile: Dockerfile
    ports:
      - "3000:4173" # Vite preview runs on 4173, exposed on port 3000
    depends_on:
      - server

  server:
    build:
      context: ./tmdb-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - seeder

  seeder:
    build:
      context: ./seeder
      dockerfile: Dockerfile
    entrypoint: sh -c "sleep 15 && ts-node seeders/seeder.ts"
