services:
  mysql:
    image: mysql:latest
    container_name: tmdb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tmdbDatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  seeder:
    container_name: seeder
    build:
      context: ./seeder
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./seeder/.env
    environment:
      MYSQL_URL: mysql://root:password@mysql:3306/tmdbDatabase
      SEED_ONLY_EMPTY: "true"
    networks:
      - backend

  tmdb-server:
    container_name: tmdb-server
    build:
      context: ./tmdb-server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    command: sh -c "sleep 10 && npm start" # Simple delay approach
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/tmdbDatabase
      NODE_ENV: development # Add this for more verbose logging
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    volumes:
      - ./tmdb-server:/app

  tmdb-client:
    container_name: tmdb-client
    build:
      context: ./tmdb-client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - tmdb-server
    ports:
      - "3000:3000"
    networks:
      - frontend
    volumes:
      - ./tmdb-client:/app
      - tmdb_client_node_modules:/app/node_modules

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend

  tmdb-server-test:
    build:
      context: ./tmdb-server
    working_dir: /app
    command: sh -c "npx wait-on tcp:mysql:3306 && npm test"
    volumes:
      - ./tmdb-server:/app
    environment:
      - NODE_ENV=test
      - DATABASE_URL=mysql://root:password@mysql:3306/tmdbDatabase
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:
  tmdb_client_node_modules:

networks:
  backend:
  frontend:
