services:
  mysql:
    image: mysql:latest
    container_name: tmdb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tmdbDatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  seeder:
    container_name: seeder
    build:
      context: ./seeder
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_URL: mysql://root:password@mysql:3306/tmdbDatabase
    networks:
      - backend

  tmdb-server:
    container_name: tmdb-server
    build:
      context: ./tmdb-server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    command: sh -c "sleep 10 && npm start" # Simple delay approach
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/tmdbDatabase
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    volumes:
      - ./tmdb-server:/app

  tmdb-client:
    container_name: tmdb-client
    build:
      context: ./tmdb-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
    volumes:
      - ./tmdb-client:/app
      - tmdb_client_node_modules:/app/node_modules
    environment:
      VITE_API_URL: http://localhost:5000
      CHOKIDAR_USEPOLLING: true
    # depends_on:
    #   - tmdb-server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:
  tmdb_client_node_modules:

networks:
  backend:
  frontend:
